// Code generated by jzero. DO NOT EDIT.
package plugins

import (
	"github.com/zeromicro/go-zero/rest"
	"github.com/jzero-io/jzero-admin/server/server/svc"
)

type CoreSvcCtx = svc.ServiceContext

func LoadPlugins(server *rest.Server, svcCtx CoreSvcCtx)	{}
